# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Kithdara Hansamal/Downloads/SOC/SOC/SOC.srcs/sources_1/ip/Block_RAM/Block_RAM.xci
# IP: The module: 'Block_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Kithdara Hansamal/Downloads/SOC/SOC/SOC.srcs/sources_1/ip/Block_RAM/Block_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_RAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Kithdara Hansamal/Downloads/SOC/SOC/SOC.srcs/sources_1/ip/Block_RAM/Block_RAM.xci
# IP: The module: 'Block_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Kithdara Hansamal/Downloads/SOC/SOC/SOC.srcs/sources_1/ip/Block_RAM/Block_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_RAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
